### ISSUE TITLE
หน้า dentist รายคนเบี้ยวตอนซ่อนปุ่ม select

### ISSUE THREAD

**Issue by Natpon** [2110503TACEDT66/cedt-se-project-dentnutz#22]
https://cedt-se-project-dentnutz-frontend.vercel.app/dentist/660184ca725eea4b26d90b36 ของกูเบี้ยวแค่อันนี้อันเดียวอันอื่นปกติ

**Comment by Natpon** [comment]
น่าจะเพราะความสูงของภาพ ฝากแก้ด้วยกูไม่เก่ง css

**Comment by SirateeTopradit** [comment]
แก้และ

**Comment by SirateeTopradit** [comment]
https://github.com/2110503TACEDT66/cedt-se-project-dentnutz/commit/cfa6073d7bfc960ae937c4cd25608a2ad88c695b
